### ISSUE TITLE
Using deepGPy choleskies?

### ISSUE THREAD

**Issue by mathDR** [SheffieldML/deepGPy#4]
In coldeep.py there is a line:

from GPy.util.choleskies import indexes_to_fix_for_low_rank

But within the package there is a choleskies.py file containing the same function.  Do you mean to use the GPy version?

**Comment by jameshensman** [comment]
Hi Dan,

Yeah, there's some functionality that was written for DeepGPy that I later
moved (copied) into GPy because it was more generally useful, so sometimes
there will be a clash.

Cleaning up DeepGPy is on the agenda!

James.

**Comment by mathDR** [comment]
Sounds good James.  Does this still imply that the devel branch of GPy is the one to link to?  Or will you be linking to the master branch after the cleanup?

And I think we can close this issue.

Dan

**Comment by jameshensman** [comment]
Hi Dan,

I think everything should work with GPy 0.8 now.

James.
