### ISSUE TITLE
Running deepGPy on OSX

### ISSUE THREAD

**Issue by li-xia** [SheffieldML/deepGPy#8]
Hi guys,

I was trying to use deepGPy on OSX, I noticed that the code attempts to use openMP which is not supported by OSX (it uses LLVM) which throws error of `<omp.h> not found`. So I used a Homebrew version Clang version wrapper clang-omp and manually copied the header file and some libs to the include path of my python env. 

The code (I used 'step_fn_demo.py') finally works without using 'extra_link_args' and 'Libraries'. I was wondering is this a right way to put up deepGPy on OSX? 

Many thanks.

**Comment by lawrennd** [comment]
Sounds fine! Would you be able to submit your process to the README as a
pull request?

Neil

**Comment by li-xia** [comment]
It's done. I have created a brunch and merged. Thanks for the reply.

**Comment by lawrennd** [comment]
Thanks Harvey! I've accepted the pull request.
